### ISSUE TITLE
keyboard nav

### ISSUE THREAD

**Issue by Noitidart** [carloluis/ssuggestor#41]
# Select an issue type

- [ ] bug
- [x] new feature

---

### Version

---

### Description

Would be awesome if can use up/down and enter key to select.

**Comment by carloluis** [comment]
Hi @Noitidart, thanks to stop by and ask.
> Would be awesome if can use up/down and enter key to select.

Right now this is a current behavior of the component.
- Are you using the latest version? [0.6.0](https://www.npmjs.com/package/ssuggestor)
- Check if you aren't disabling keys by setting the `useKeys` prop _off_. By default it's _on_.

Please, check console in [this pen](https://codepen.io/carloluis/pen/rjpLYw?editors=0011) when performing those steps and let me know if I missunderstood your issue.

**Comment by carloluis** [comment]
Closing this issue because no further explanation received. 
@Noitidart feel free to reopen this or contribute solving any issue / proposal.
Cheers!

**Comment by Noitidart** [comment]
Thanks @carloluis ! I was just trying the demo, I was testing it in Firefox. Im not sure why keys didnt work. I tried it again and it works! Thanks for this awesome module!
